### ISSUE TITLE
Add bevy with features as a dependency instead of specifying individual bevy crates

### ISSUE THREAD

**Issue by DavidHospital** [jakobhellermann/bevy-inspector-egui#236]
Currently in `main`, (b203ca5c3f688dddbe7245f87bfcd74acd4f5da3 as of today), the following dependencies are listed in the `bevy-inspector-egui` crate:
```toml
bevy_app = { version = "0.15.0" }
bevy_asset = { version = "0.15.0" }
bevy_color = { version = "0.15.0" }
bevy_core = { version = "0.15.0" }
bevy_ecs = { version = "0.15.0" }
bevy_hierarchy = { version = "0.15.0" }
bevy_log = { version = "0.15.0" }
bevy_math = { version = "0.15.0" }
bevy_reflect = { version = "0.15.0" }
bevy_state = { version = "0.15.0" }
bevy_time = { version = "0.15.0" }
bevy_utils = { version = "0.15.0" }
bevy_window = { version = "0.15.0" }

bevy_render = { version = "0.15.0", optional = true }
bevy_core_pipeline = { version = "0.15.0", optional = true }
bevy_pbr = { version = "0.15.0", optional = true }
bevy_image = { version = "0.15.0", optional = true }
```

In my opinion, specifying a single `bevy` dependency with selected features would be nicer, if that is possible here (maybe there is a good reason why it's not).
The reason I propose this change, is that it is currently very difficult to patch the `bevy` dependency in a project which also uses `bevy-inspector-egui`. For example, if I have my own fork of Bevy which fixes a few things, I would love to be able to add:
```toml
[patch.crates-io]
bevy = { git = "https://github.com/<Me>/bevy", branch = "<my-branch>" }
```
However, since `bevy-inspector-egui` does not declare the dependency, `bevy`, Cargo will still resolve all the Bevy crates it declares from `crates.io`, instead of from my fork. I would need to add a patch entry for each Bevy crate declared here.

Please let me know if this is feasible to change, or if there is something I am missing which would make patching `bevy` like this easy.
