### ISSUE TITLE
How to enable "picking" feature from bevy_egui?

### ISSUE THREAD

**Issue by muhuk** [jakobhellermann/bevy-inspector-egui#254]
I tried adding `bevy_egui` as a dependency (even though I only use it via inspector:

```toml
# Cargo.toml

[dependencies]
# ...
bevy_egui = { version = "0.34.0", features = ["picking"], optional = true }
bevy-inspector-egui = { version = "0.31.0", optional = true }
# ...

[features]
# ...
inspector = ["dep:bevy-inspector-egui", "bevy_egui/picking"]
# ...
```

(`inspector` feature is enabled)

I still get the old behavior where clicking on inspector is also registered as a click on my UI. I was hoping to prevent this by enabling `"bevy_egui/picking"`.
