### ISSUE TITLE
Rapier2D components

### ISSUE THREAD

**Issue by no-materials** [jakobhellermann/bevy-inspector-egui#36]
Thanks for the great crate. I am currently facing an issue while trying to inspect rapier2D-specific components such as `RigidBodyPosition` or `ColliderType`. The message *Inspectable has not been defined for this component* is shown, even though:

* I am compiling with the `rapier2d` feature set:
```toml
bevy-inspector-egui = { version="0.6.1", features=["rapier2d"]}
```
* I am using the `WorldInspectorPlugin`
```rust
app.add_plugin(WorldInspectorPlugin::new());
```

Is there anything I am missing in order to get this going?

**Comment by Luminoth** [comment]
It looks like rapier support might have been removed for now? Just from looking at the Cargo.toml here.

**Comment by lemunozm** [comment]
Hi, is there any reason why rapier support is removed? Is there any workaround?

**Comment by jakobhellermann** [comment]
I removed it when releasing a version compatible with bevy 0.6 because at that point there was no compatible bevy_rapier version yet.

I also wanted to decouple bevy-inspector-egui releases from bevy_rapier, so I experimented with a separate integration crate: https://github.com/jakobhellermann/bevy-inspector-egui/tree/external-rapier/integrations/bevy-inspector-egui-rapier. You can try that and let me know how it works for you.

```toml
bevy-inspector-egui-rapier = { git = "https://github.com/jakobhellermann/bevy-inspector-egui", branch = "external-rapier", features = ["rapier3d"] }
```

**Comment by jakobhellermann** [comment]
I was gonna release that version on crates.io once rapier 0.12 is out of alpha but if that takes a while it might be worth publishing already and doing an update when rapier releases.

**Comment by lemunozm** [comment]
Hi @jakobhellermann,

I tested the example (rapier2d) on the repo and it works fine 😃. Nevertheless, if I copy that example out of the repo, the components are not inspectable. I'm not sure if is something related to depdendencies, but I think I have the correct ones:
```toml
bevy = { version = "0.6.0", features = ["dynamic"] }
bevy_rapier2d = "0.12"
bevy-inspector-egui = "0.8"
bevy-inspector-egui-rapier = { git = "https://github.com/jakobhellermann/bevy-inspector-egui", branch = "external-rapier", features = ["rapier2d"] }
```

**Comment by jakobhellermann** [comment]
Are you using the world inspector or something like a `InspectorQuery`?

The external bevy-inspector-egui-rapier crate doesn't actually implement `Inspectable` for the rapier types (this isn't allowed because of the [orphan rules](https://github.com/Ixrec/rust-orphan-rules)), but just 'registers' the types so that they can be displayed in the world inspector. My guess was that this is fine because most people won't have rapier types in their resources, they just want to inspect the ones already in the world.

**Comment by lemunozm** [comment]
Hi,

I'm using exactly the rapier2d example but from copied into my crate. A copy-paste without any modification, so my inspectors are:
```rust
        .add_plugin(RapierPhysicsPlugin::<NoUserData>::default())
        .add_plugin(WorldInspectorPlugin::new())
        .add_plugin(bevy_inspector_egui_rapier::InspectableRapierPlugin)
```

Regarding what you say, if `Inspectable` is not allowed, can I do something in order to inspect some properties of a rapier component? any workaround? I would expect that my app would behave like in the example.

**Comment by jakobhellermann** [comment]
In what way exactly is it not working? Do you see the world inspector but can't edit the components?
For reference, this is what I would expect the world inspector to look like:
![image](https://user-images.githubusercontent.com/22177966/154686218-8e6d7ebe-3a40-4ad3-9062-c1ce12a3ca6b.png)

**Comment by lemunozm** [comment]
Sorry, maybe I did not explain well the error. I share the same capture:

![issue](https://user-images.githubusercontent.com/15687891/154688431-863db3fb-0244-4709-be86-17a5326a34c9.png)

The same message appears in all rapier components. I would expect the behavior to be the same as yours.

**Comment by jakobhellermann** [comment]
Can you post the output of
```sh
cargo tree -i rapier2d
cargo tree -i bevy
cargo tree -i bevy-inspector-egui
```
?

I suspect that there are multiple versions of one of these crates active or something like that.

**Comment by lemunozm** [comment]
Your suspects are right!

```
  bevy-inspector-egui:0.8.1                                                                                            │
  bevy-inspector-egui:0.8.2
```

I will check what is happing 😵‍💫

**Comment by lemunozm** [comment]
At Cargo.toml:
```toml
bevy = { version = "0.6.0", features = ["dynamic"] }
bevy_rapier2d = "0.12"
# bevy-inspector-egui = "0.8" # Removed
bevy-inspector-egui = { git = "https://github.com/jakobhellermann/bevy-inspector-egui", branch = "external-rapier" } # Added
bevy-inspector-egui-rapier = { git = "https://github.com/jakobhellermann/bevy-inspector-egui", branch = "external-rapier", features = ["rapier2d"] }
```

Fixed the issue removing the commented line and adding the next one. 

Thanks for the help!
